### PR TITLE
Update default Nasm version from 2.14.02 to 2.15.05

### PR DESCRIPTION
**Pull request by EwoutH**

### CODE REVIEW

**Comment by EwoutH** [comment]
Nasm now sometimes seems packed into` nasm-$version`, but also sometimes into  `nasm-nasm-$version`. Very confusing.

**Comment by ilammy** [comment]
> Nasm now sometimes seems packed into nasm-$version, but also sometimes into nasm-nasm-$version. Very confusing.

That seems to have been some error for the latest release since now it's downloaded fine.

However, 2.15.05 still fails to build from source (everywhere), and all with the same `configure` error.

From my local experimentation, it seems that there are more files that need to get their DOS line endings to be converted into UNIX ones so that the shell does not choke on them.

It seems that ZIP files use DOS endings while tarballs use UNIX endings uniformly. I don't remember why ZIP files are downloaded, really. Probably because they were easier for me back then to unpack. I guess, switching to downloading tarballs should avoid having to convert line endings in a gazillion of files.

**Comment by ilammy** [comment]
I've merged the updated `master` branch into your branch, that should make the builds green now (will merge after CI passes). I've also updated the version in README for consistency.

**Comment by ilammy** [comment]
Thanks again for keeping things up-to-date, @EwoutH!

**Comment by EwoutH** [comment]
Thanks for unblocking this PR with #10!

**Pull request merged**
